set(STM32_HAL_SRC
${STM32_HAL_PATH}/Src/stm32wbxx_hal_adc.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_adc_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_comp.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_cortex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_crc.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_crc_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_cryp.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_cryp_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_dma.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_dma_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_exti.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_flash.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_flash_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_gpio.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_hsem.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_i2c.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_i2c_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_ipcc.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_irda.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_iwdg.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_lcd.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_lptim.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_pcd.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_pcd_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_pka.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_pwr.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_pwr_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_qspi.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_rcc.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_rcc_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_rng.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_rtc.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_rtc_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_sai.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_sai_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_smartcard.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_smartcard_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_smbus.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_smbus_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_spi.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_spi_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_tim.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_tim_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_tsc.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_uart.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_uart_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_usart.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_usart_ex.c
${STM32_HAL_PATH}/Src/stm32wbxx_hal_wwdg.c
)

add_library(stm32_hal STATIC ${STM32_HAL_SRC})