set(STM32_HAL_SRC
${STM32_HAL_PATH}/Src/stm32wlxx_hal_adc.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_adc_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_comp.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_cortex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_crc.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_crc_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_cryp.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_cryp_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_dac.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_dac_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_dma.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_dma_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_exti.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_flash.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_flash_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_gpio.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_gtzc.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_hsem.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_i2c.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_i2c_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_i2s.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_ipcc.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_irda.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_iwdg.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_lptim.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_pka.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_pwr.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_pwr_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_rcc.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_rcc_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_rng.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_rng_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_rtc.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_rtc_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_smartcard.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_smartcard_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_smbus.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_smbus_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_spi.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_spi_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_subghz.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_tim.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_tim_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_uart.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_uart_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_usart.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_usart_ex.c
${STM32_HAL_PATH}/Src/stm32wlxx_hal_wwdg.c
)

add_library(stm32_hal STATIC ${STM32_HAL_SRC})