set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR ARM)

if(NOT ARM_TOOLCHAIN_PATH)
message(FATAL_ERROR "\n<<<<<<<<<<<<<<<<<<<< ERROR >>>>>>>>>>>>>>>>>>>>\ARM_TOOLCHAIN_PATH is not set!\n<<<<<<<<<<<<<<<<<<<< ERROR >>>>>>>>>>>>>>>>>>>>\n")
endif()

set(TOOLCHAIN_PREFIX arm-none-eabi)

if(WIN32)
set(EXT .exe)
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER ${ARM_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-gcc${EXT})
set(CMAKE_CXX_COMPILER ${ARM_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-g++${EXT})
set(CMAKE_ASM_COMPILER ${ARM_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-gcc${EXT})

set(CMAKE_OBJCOPY ${ARM_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-objcopy${EXT} CACHE INTERNAL "objcopy command")
set(CMAKE_OBJDUMP ${ARM_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-objdump${EXT} CACHE INTERNAL "objdump command")
set(CMAKE_GDB ${ARM_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-gdb${EXT})
set(CMAKE_SIZE ${ARM_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-size${EXT})

