set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR ARM)

if(NOT ARMORY_TOOLCHAIN_PATH)
message(FATAL_ERROR "\n<<<<<<<<<<<<<<<<<<<< ERROR >>>>>>>>>>>>>>>>>>>>\ARMORY_TOOLCHAIN_PATH is not set!\n<<<<<<<<<<<<<<<<<<<< ERROR >>>>>>>>>>>>>>>>>>>>\n")
endif()

set(TOOLCHAIN_PREFIX arm-none-eabi)

if(WIN32)
set(EXT .exe)
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER ${ARMORY_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-gcc${EXT})
set(CMAKE_CXX_COMPILER ${ARMORY_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-g++${EXT})
set(CMAKE_ASM_COMPILER ${ARMORY_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-gcc${EXT})

set(CMAKE_OBJCOPY ${ARMORY_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-objcopy${EXT} CACHE INTERNAL "objcopy command")
set(CMAKE_OBJDUMP ${ARMORY_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-objdump${EXT} CACHE INTERNAL "objdump command")
set(CMAKE_GDB ${ARMORY_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-gdb${EXT})
set(CMAKE_SIZE ${ARMORY_TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-size${EXT})

